name: Gauge Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./testing

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Gauge
      run: |
        npm install -g @getgauge/cli
        gauge install js
        gauge install html-report

    - name: Install Dependencies
      run: npm install

    - name: Run Gauge Tests
      run: gauge run specs/

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gauge-test-results
        path: ./testing/reports/html-report